sudo: true
language: php
php:
- 7.0
notifications:
  email: false
before_script:
- phpenv config-rm xdebug.ini
- mkdir plugins
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0
- chmod 777 ci.sh
script:
- "./ci.sh"
deploy:
  provider: releases
  api_key:
    secure: H2hb1saIN4R/Y/bMH2QdizuIzoPV0s+4+NnyCpS9JY/lhgfnBrRziv+cfux3GeRwhmLmsSXzAfPXR8ZPmfKWr8qIu3DZ4ugA2dBMTE3baWbU9j0et2O8wv68qU8bdWoUN7OVSToouTYYKxY5Q2mDDc/uvKJflUb4rx8FgkCg+WF4VhKqfEfQfi8gQHPXz8+85eiTAK4GhrKf7CHQ8cUvzQZbeAHgQl3DhpvoC2et5dkd4NoXEG1Ppo8KUkBcUr21RMIImr++fa8OMEMvDThgszb0ng1raNk3kq9v4V0nVNUzhaAx2sHS1Vp09lhFV9kPaeQhyHO6J83zx2DAEUae/zZNKsnemNY88T5W67GmU7gqF+A4rpdp27ih9tmAf6ukiOjd1Zqlmz4DZVfIma1hGeCvxr5ApT0DpJDui9brWdIWhyfiSpA5UcQ67SCUb4kesRhvsYMjEdHr1mpXZRaSAqOiXdcJKkByV4RM6SJhr5lPncePLqMC9vpHGy3AA3GZcfmmkJrzD9qXeFw8CnbylYwYiAeP+BVuihWdfzCIFC+x0JB5hu7zqllqcuFGUIdxtqDYMdNvOlVqyiS3WBJSJ5snltx3vxcqXU1G+zp4dklJvZIbvjGtqGqJnw/9pWkGptybBLMBvs3W7fSYexgphhNDhG1iSQE60gYJanWG0Lo=
  file: Tesseract_1.2.1.phar
  skip_cleanup: true
  on:
    tags: true
